<?php

namespace AppBundle\Repository;

/**
 * LeafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeafRepository extends \Doctrine\ORM\EntityRepository
{
}
